sudo: required

language: generic

services:
  - docker

os:
  - linux

before_script:
  # Environment variables
  - export TRAVIS_TAG=travis-${TRAVIS_BUILD_ID}
  - export BRANCH=${TRAVIS_BRANCH/\//-}
  - export COMMIT=${TRAVIS_COMMIT::7}

  # Login to docker repository
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
  # Build Pharo 5.0 docker images
  - export IMAGE_REPOSITORY=${DOCKER_USERNAME}/teamtalk-server
  - docker build -t ${IMAGE_REPOSITORY}:${TRAVIS_TAG} .
  - docker tag ${IMAGE_REPOSITORY}:${TRAVIS_TAG} ${IMAGE_REPOSITORY}:${BRANCH}
  - docker tag ${IMAGE_REPOSITORY}:${TRAVIS_TAG} ${IMAGE_REPOSITORY}:${COMMIT}
  - docker push ${IMAGE_REPOSITORY}